### ISSUE TITLE
does not work  wardrobe 

### ISSUE THREAD

**Issue by genrihx2** [CaveeJohnson/wardrobe#3]
![image](https://user-images.githubusercontent.com/3043207/191684175-12c1485c-be24-4f1c-87f6-76017d76a848.png)

**Comment by CaveeJohnson** [comment]
![191684175-12c1485c-be24-4f1c-87f6-76017d76a848](https://user-images.githubusercontent.com/8331733/191697793-e038d920-a1c0-4514-b215-221eafc8dbca.png)
